apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default
subjects:
- kind: User
  name: jane
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #This must be Role ro ClusterRole
  name: pod-reader #This must match the name of Role or ClusterRole to bind
  apiGroup: rbac.authorization.k8s.io
