---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simpleapp
data:
  # property-like keys; each key maps to a simple value
  app_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  simpleapp.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true 

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP-COLOR: blue
  APP-MODE: prod
