apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp
  labels:
    app: simpleapp-deployment

spec:
  replicas: 5
  selector:
    matchLabels:
      app: simpleapp-deployment

  template:
    metadata:
      labels:
        app: simpleapp-deployment

    spec:
      containers:
      - name: simpleapp-container-deployment
        image: 9538253250/simpleapp:venv1
        ports:
          - containerPort: 8000
        env:
         - name: APP_COLOR
           value: red
#        volumeMounts:
#          - mountPath: "/opt/data"
#            name: simpleapp-storage
#      volumes:
#        - name: simpleapp-storage
#          persistentVolumeClaim:
#            claimName: simpleapp-pv-claim 

