apiVersion: v1
kind: Pod
metadata:
  name: simpleapppod
  labels:
    name: simpleapp

spec:
  containers:
    - name: simpleapp-container
      image: 9538253250/simpleapp:latest
      ports:
        - containerPort: 8000
