apiVersion: v1
kind: Service
metadata:
  name: simpleapp
  labels:
    app: simpleapp-deployment
spec:
  ports:
  - port: 8000
    protocol: TCP
    nodePort: 30000
  selector:
    app: simpleapp-deployment
  #type: NodePort
  type: LoadBalancer

#kubectl get svc simpleapp -> to get NodePort
#http://minikubeip:nodeport
#minikube service simpleapp --url
